# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 05:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arquivo', '0004_cardplayed_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardplayed',
            name='match',
        ),
        migrations.RemoveField(
            model_name='cardplayed',
            name='user',
        ),
        migrations.RemoveField(
            model_name='match',
            name='blue_played_cards',
        ),
        migrations.RemoveField(
            model_name='match',
            name='red_played_cards',
        ),
        migrations.RemoveField(
            model_name='match',
            name='user',
        ),
        migrations.DeleteModel(
            name='CardPlayed',
        ),
        migrations.DeleteModel(
            name='Match',
        ),
    ]
