# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.1

      # MySQL is the main source for django
      - image: circleci/mysql:latest
        environment:
        - MYSQL_ROOT_HOST=%

      # MongoDB to keep matches and cards used in matches
      - image: circleci/mongo:3.5

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            sudo apt-get install zip
            python3 -m venv venv
            . venv/bin/activate
            pip install -r dev-requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      # run tests!
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:3306 -timeout 1m
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python manage.py test -v 2 --settings=settings.circleci

      - run:
          name: save test reports
          command: |
            zip -r /home/circleci/repo/reports/test_report.zip /home/circleci/repo/reports/cover
            rm -rf /home/circleci/repo/reports/cover

      - run:
          name: save the project
          command: |
            rm -rf venv
            zip -r /home/circleci/repo/reports/$CIRCLE_PROJECT_REPONAME-$CIRCLE_BUILD_NUM.zip /home/circleci/repo/

      - store_artifacts:
          path: reports/
          destination: test_report_1
      - store_test_results:
          path: reports/